import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Authentichef",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <link rel="icon" href="https://authimages.s3.eu-west-2.amazonaws.com/Fav+icon+(1).png" sizes="any" />
      <body className={inter.className}></body>
      <Providers >{children}</Providers>
    </html>
  );
}
